# Application
spring.application.name=tsinjo-std21001

# Profiles
spring.profiles.active=@spring.profiles.active@

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Vola API
vola.api.key=${VOLA_API_KEY}
vola.api.base-url=https://42cwka3n4ifcp7ufheyrpmph240iuaxo.lambda-url.eu-west-3.on.aws

# Flyway
spring.flyway.locations=classpath:/db/migration
